### ISSUE TITLE
Use environment variables to customize target location

### ISSUE THREAD

**Issue by cdaguerre** [drone-plugins/drone-s3#16]
Sorry if this is obvious, but I couldn't find the answer anywhere.
Is it possible to use drone environment variables in the target location?
I'd like to be able to set something like:
```yaml
publish:
  s3:
    target: /drone/$CI_REPO/$CI_BUILD_NUMBER/
```
