### ISSUE TITLE
Support storage class

### ISSUE THREAD

**Issue by alkalinecoffee** [drone-plugins/drone-s3#52]
The plugin should support specifying a storage class.  This allows users to upload artifacts to lower cost storage backends.

From the [CLI docs](https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html):

```
--storage-class (string) The type of storage to use for the object.
  Valid choices are: STANDARD | REDUCED_REDUNDANCY | STANDARD_IA | ONEZONE_IA.
  Defaults to 'STANDARD'
```

**Comment by tboerger** [comment]
After merging https://github.com/drone-plugins/drone-s3/pull/62 you should be able to use a setting like this:

```
- name: s3 upload
  image: plugins/s3
  settings:
    storage_class: GLACIER
    ... 
```
